### ISSUE TITLE
packed-refs are ignored when listing remote branches

### ISSUE THREAD

**Issue by scholzb-hb** [hraban/tomono#32]
The function `remote-branches` has a bug which may lead to missing branches and/or subtrees in the monorepo.

The file-based approach for listing all branches for a given remote does not consider packed-refs. The Git GC (garbage collector) may occasionally pack individual ref files into a single file named `.git/packed-refs` and remove them from the `refs` directory. Those refs will be ignored by tomono.

Further information:
* https://git-scm.com/docs/git-pack-refs
* https://git-scm.com/book/en/v2/Git-Internals-Maintenance-and-Data-Recovery

For now we cannot provide any steps to reproduce, but it seems that the issue is related to the number and size of the repositories to process. In our case, we migrated ~100 single repositories with a total of ~125000 commits and ~1400 remote branches into a monorepo, when we detected that the content of a certain single repository was missing.

**Comment by scholzb-hb** [comment]
The same problem may occur when creating the namespaced tags. The tags within `.git/packed-refs` are ignored in this case.

**Comment by pcentgraf** [comment]
The easiest way to work around this is to disable gc-auto right after creating the new repository, like so:

	git init --bare .git

	# we don't want pack-refs to run and break our flow
	git config gc.auto 0

Then at the end of the main function, re-enable gc.auto. I also recommend running a full GC to optimize the resulting monorepo.

	# optimize the git storage files
	git config --unset gc.auto
	git gc --aggressive

**Comment by hraban** [comment]
This was fixed for branches but is still an issue for tags.
