### ISSUE TITLE
Ownership Transfer

### ISSUE THREAD

**Issue by icio** [hraban/tomono#33]
Hey @hraban, I don't think anyone here at Ravelin knows much about tomono, though we're greatful for the monorepo that it's given us. As you're the most active here in replying to issues and pull requests, would you be interested in us transferring ownership to you?

**Comment by hraban** [comment]
Hi @icio , sure thing. 👍

**Comment by icio** [comment]
Ah, I got the following error:

> hraban/tomono already exists and You can only transfer a repository from an organization to yourself at this time 

I think if you delete your fork I can transfer from the organisation to myself, and then to you.

**Comment by hraban** [comment]
done

**Comment by icio** [comment]
You should have the transfer request now :)

**Comment by hraban** [comment]
thanks for sorting it out! see you. p.s. tell Raph I said hi, and ask him about the 26th of October. you should come round if you have time :)
