### ISSUE TITLE
How to sync the new branches of the subrepos after migration?

### ISSUE THREAD

**Issue by leaflinfeng** [hraban/tomono#38]
Hello:
I have two subrepos named repo1 and repo2 with branch master/dev。After the migration，the monorepo have branch master/dev。After that，the repo1 and repo2 create new branch dev_new。How can monorepo sync the new branch dev_new？
Thanks

**Comment by hraban** [comment]
Hi, this is a great question, thank you for asking. I just pushed a change that enables this: the remotes are now setup such that all you need to do is:

`git fetch --all`

And it will automatically fetch new tags in the correct namespace.
