### ISSUE TITLE
error: invalid path on Windows (carriage-return issue)

### ISSUE THREAD

**Issue by asinning** [hraban/tomono#44]
To run this on Windows I needed to use:
``` cat config.txt | tr -d '\r' | ./tomono```
Without the middle section, `read-tree` failed with `error: invalid path '{repopath} ?/.{first-file-in-repo}'`. This is because the \r before \n gets included in $repopath.

**Comment by hraban** [comment]
Iiiiinteresting.

I'm surprised that is all it took to make the script work on windows 😂 I consider this a win.
