### ISSUE TITLE
Combine into monorepo - same git name

### ISSUE THREAD

**Issue by maximbaran** [hraban/tomono#50]
I'm facing problems with merging this repos (I guess that this is happen bacause **Algorithm.git** is the same)

```
tomono <<EOF
git@XXXX:/home/git/projects/Algorithm.git Algorithm_1
git@YYYY:/home/git/projects/Algorithm.git Algorithm_2
EOF
```

![image](https://user-images.githubusercontent.com/43070955/204127267-2ab4c271-f841-4428-bc26-3b91263c31e5.png)

**Comment by hraban** [comment]
Hi,

I just tried this locally with two aliases for github.com (host-a and host-b) and it worked:

```
mbp15-2203:tmp hraban$ (echo git@host-a:hraban/opus Algorithm_1 ;  echo git@host-b:hraban/opus Algorithm_2 ) | $OLDPWD/tomono
Initialized empty Git repository in /private/tmp/core/.git/
remote: Enumerating objects: 646, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 646 (delta 9), reused 16 (delta 6), pack-reused 619
Receiving objects: 100% (646/646), 798.33 KiB | 680.00 KiB/s, done.
Resolving deltas: 100% (411/411), done.
From host-a:hraban/opus
 * [new branch]      goversion  -> Algorithm_1/goversion
 * [new branch]      v1         -> Algorithm_1/v1
 * [new branch]      v2         -> Algorithm_1/v2
From host-b:hraban/opus
 * [new branch]      goversion  -> Algorithm_2/goversion
 * [new branch]      v1         -> Algorithm_2/v1
 * [new branch]      v2         -> Algorithm_2/v2
Updated 40 paths from the index
mbp15-2203:tmp hraban$ tree core
core
├── Algorithm_1
│   ├── AUTHORS
│   ├── LICENSE
...
```

So I'm not sure that's the problem. As long as XXX and YYY are different, and the repo nicknames (Algorithm_{1,2}) are different, it should be fine.

Is the only difference them maybe the capitalisation of the remote name? It looks like you're on Windows, which is case insensitive, and git might not expect that.

**Comment by hraban** [comment]
Any updates? Was it a case sensitivity issue?

**Comment by hraban** [comment]
feel free to reopen if you have more info or any updates
