### ISSUE TITLE
How to handle ambiguous refname

### ISSUE THREAD

**Issue by elijahmorg** [hraban/tomono#53]
I am working on merging multiple long lived repos together.

Unfortunately in many places they have a branch name and tag with the same name. This causes this warning/error to be thrown

```
warning: refname 'reponame/branchname' is ambiguous.
fails here2?
warning: refname 'reponame/branchanme' is ambiguous.
fatal: sha1commithash is not a valid 'commit' object
```

The `the fails here2?` print comes after this line.
https://github.com/hraban/tomono/blob/master/tomono#L73

Is there a programmatic way to handle this?

I started looking at this and trying to use "refs/heads/" in order to use the fully qualified branch name, but I don't understand this well enough yet to get that to work.
https://stackoverflow.com/questions/28192422/git-warning-refname-xxx-is-ambiguous

**Comment by hraban** [comment]
Close--it's `refs/remotes/..`.

**Comment by elijahmorg** [comment]
The updated script worked! Many thanks.

**Comment by hraban** [comment]
Thank you for the tip 🙏
