### ISSUE TITLE
How do I push a full history?

### ISSUE THREAD

**Issue by dekinet** [hraban/tomono#58]
Hi, thanks for your efforts in creating this great tool. I've been using it successfully so far, but have hit an issue I'm not sure how to work through.

I have created a fork of mulitple private GitHub repositrories belonging to a client, with the intention of merging them into a monorepo. Following the instructions of the tomono tool, I've been able to do just that. If I run `git log` in the appropriate branch of the monorepo, in my local workarea, I can see a merged history of each repo that was pulled in going back to the start of time. Interestingly (to me, perhaps this is expected) I can checkout `monorepo:main` and see the _same_ history log that I do for `monorepo:develop`.

The tomono tool created remote (not local) branches for each of the imported repos:
``$ git branch -a | grep libA
remotes/libA/develop
remotes/libA/main
``

In my local repo, I can checkout `monorepo:libA/develop`, getting a message that I'm now in a detached HEAD state. Running `git log`, I see the history of the original repo that was used to create that branch. 

In GitHub, I can see branches available matching the branches of the various imported repos. However, I cannot see the new branches that were created for importing the various repos (like `libA/develop`). I created a PR to merge work into the upstream repo, and the `libA/develop` branch cannot be seen there either. 

I'm curious if this is all expected or if I have done something wrong? What is the best practice when creating a new monorepo to ensure the history of the various imported repos is maintained and accessible to all who need to be able to see it?

Thanks.

**Comment by hraban** [comment]
Hi dekinet, sorry I'm not sure I follow the problem description entirely but here's my best guess: once you're done merging everything in, you can do `git push --all origin` to push all your branches to origin. Hope that helps 👍

**Comment by dekinet** [comment]
Sorry, I'm probably lacking the git vocabulary to adequately describe what's going on. I have tried `git push --all origin` and it says "Everything is up to date". 

I can do this:
```
[mypc] ~/repos/monorepo (develop) ⚡
❯ git branch | grep libA

[mypc] ~/repos/monorepo (develop) ⚡
❯ git branch -a | grep libA
  remotes/libA/develop
  remotes/libA/main
```

And if I do this:
```
[mypc] ~/repos/monorepo (develop) ⚡
❯ git remote -v
app1     git@github.com:dk/app1.git (fetch)
app1     git@github.com:dk/app1.git (push)
libA      git@github.com:dk/libA.git (fetch)
libA      git@github.com:dk/libA.git (push)
libB        git@github.com:dk/libB.git (fetch)
libB        git@github.com:dk/libB.git (push)
origin  git@github.com:dk/monorepo.git (fetch)
origin  git@github.com:dk/monorepo.git (push)
```

If I run `git log <monorepo>/app1/src/file1`, the only history I get is one entry generated by the tomono tool with the comment `Move all files to app1`.

If I checkout branch `app1/develop`, the `src` folder is now at the <monorepo> root level (whereas prior to checkout it was under the app1 folder). This makes sense and I think is expected. If I run `git log` on `<monorepo>/src/file1` now, I get that file's full history. However, I cannot get that branch pushed to github (and thus not to the upstream repo) so that the owner of the upstream repo can checkout the branch and see the same history.

**Summary**
It looks like the full history of every file of every branch of every original repo is present, but all "attached" to the root of the new monorepo (if that makes sense). The history of each file is (almost) empty. In other words:

in <monorepo> root, develop branch, `git log` generates a merged history of everything that's made up the monorepo. However, `git log libA/src/file1` only produces the "Move all files to libA" output mentioned above.

Hopefully this makes sense and hasn't muddied the question even more?

**Comment by hraban** [comment]
The history issue I think is a separate one; you have to use `git log --follow` to follow renames across git. See https://git-scm.com/docs/git-log#Documentation/git-log.txt---follow

The other point I think may be a misunderstanding of what tomono does behind the scenes. What you're referring to as `libA` is a _remote_ , this is just a repo where you got all the branches, at merge time. But note that the point of tomono is to stop caring about individual remotes, and merge all their _branches_ together. So for your local branch list, you shouldn't see any `libA`, unless there was a branch on `libA` also called `libA`. Example from running the test script locally:

```
$ git branch
  branch-a
  branch-b
* master
```
Those are all the local branches. But the total list of branches, including remotes:

```
$ git branch -a
  branch-a
  branch-b
* master
  remotes/foo/branch-a
  remotes/foo/master
  remotes/中文/branch-a
  remotes/中文/branch-b
  remotes/中文/master
```

As you can see, there were two remotes: `foo` and `中文`. But they both only defined , in total, together, 3 branches: `master`, `branch-a`, and `branch-b`. The local branches are therefore just those three. The remote's names are reflected in the _fileystem_. That's why you get this:

```
$ ls -1
foo
中文
```

(On master)

Hope this helps.

**Comment by dekinet** [comment]
Thank you, that's really helpful. The `--follow` option did the trick for me, and I think resolves the misunderstanding I had about the branches.
