### ISSUE TITLE
Git Log not returning full history of files

### ISSUE THREAD

**Issue by lt9512** [hraban/tomono#6]
I have tried running the script on three repositories, which ran successfully. However when running "git log" on files, it seems we have lost the commit history of the file, apart from one commit entry which  appears to come from the script, For example running "git log somefile" in ProjectBlah we see:

.....
"Merging ProjectBlah to master"
....

However, when running "git log" on a folder it returns the expected commit history. 

Have you seen this before?

**Comment by hraban** [comment]
I had never considered this, but you're right: git log --follow doesn't follow renames during merges. The funny thing is that git blame _does_ track the history. From a cursory glance[0], Git devs seem quite apathetic about the whole --follow business, so I doubt there will ever be a solid fix for this.

Fair is fair, we should add this to the README. I'm busy right now but if you want to create a PR I'm sure they'll merge it in.

Ciao!

[0]http://git.661346.n2.nabble.com/git-log-follow-doesn-t-follow-a-rename-over-a-merge-td6480971.html
